#!/usr/bin/env perl

use v5.18.1;
use strict;
use warnings;

use JSON::MaybeXS;
use Data::Dumper;
use Solaris::kstat;
use Time::HiRes  qw( gettimeofday tv_interval clock_nanosleep );

my $fields = {
  #field => { name => { value => stat } },
  #minf  => { vm => { value => [ 'as_fault', 'hat_fault' ], }, },
  #mjf   => { vm => { value => 'maj_fault', }, },
  xcal  => { sys => { value => 'xcalls', }, },
  intr  => { sys => { value => 'intr',
                      width => 5, },
           },
  ithr  => { sys => { value => 'intrthread', }, },
  csw   => { sys => { value => 'pswitch',
                      width => 4, },
           },
  icsw  => { sys => { value => 'inv_swtch', }, },
  migr  => { sys => { value => 'cpumigrate', }, },
  smtx  => { sys => { value => 'mutex_adenters', }, },
  syscl => { sys => { value => 'syscall', }, },
  usr   => { sys => { value => 'cpu_nsec_user',
                      time  => 1, },
           },
  sys   => { sys => { value => 'cpu_nsec_kernel',
                      time  => 1, },
           },
  idl   => { sys => { value => 'cpu_nsec_idle',
                      time  => 1, },
           },
  # NOTE: This is a subset of sys / cpu_nsec_kernel
  intr  => { sys => { value => 'cpu_nsec_intr',
                      time  => 1, },
           },
};

my $k = Solaris::kstat->new();

my $i = 0;
my @data;
my $gen  = 0;

# Prime the kstat by reading the data we intend to use in this script.  In this
# case, that's cpu:<all instances>:sys
foreach my $instance ( keys %{$k->{cpu}} ) {
  () = each %{$k->{cpu}->{$instance}->{sys}};
}

# Initialize the @data array
$data[$gen ^ 1] = $k->copy();
$data[$gen] = $k->copy();

while ($i++ < 300) {
  my $t0 = [ gettimeofday ];
  $gen = $gen ^ 1;
  $data[$gen] = $k->copy();
  my $data_to_return = [];

  foreach my $cpu (sort { $a <=> $b } keys %{$data[$gen]->{cpu}}) {
    $data_to_return->[$cpu] = {};
    $data_to_return->[$cpu]->{CPU} = $cpu;
    if (defined($data[$gen ^ 1])) {
      foreach my $field ( qw(idl) ) {
        my ($name) = keys %{$fields->{$field}};
        my ($stat) = $fields->{$field}->{$name};
        # Skip if snaptimes are identical - this will always happen on the first
        # pass through this loop
        next if ($data[$gen]->{cpu}->{$cpu}->{$name}->{snaptime} ==
                 $data[$gen ^ 1]->{cpu}->{$cpu}->{$name}->{snaptime});
        #say "kstat name: $name";
        #say "kstat stat info: " . Dumper( $stat );
        #say "OLD: " . $data[$gen]->{$cpu}->{$name}->{snaptime};
        #say "NEW: " . $data[$gen ^ 1]->{$cpu}->{$name}->{snaptime};
        my $time_pct =
          (($data[$gen]->{cpu}->{$cpu}->{$name}->{$stat->{value}} -
            $data[$gen ^ 1]->{cpu}->{$cpu}->{$name}->{$stat->{value}}
           )   /
            ( $data[$gen]->{cpu}->{$cpu}->{$name}->{snaptime} -
              $data[$gen ^ 1]->{cpu}->{$cpu}->{$name}->{snaptime}
            )) * 100;
        my $rounded_pct = int($time_pct + 0.5);
        say "CPU $cpu: $field " . sprintf("%3.0f%%", $rounded_pct);
        $data_to_return->[$cpu]->{$field} = $rounded_pct;
      }
    }
  }

  say encode_json( $data_to_return );
  sleep(1);
  $k->update();
  my $t1 = [ gettimeofday ];
  my $elapsed = tv_interval( $t0, $t1 );
  say "ELAPSED: $elapsed";
}
