#!/usr/bin/env perl

use v5.18.1;
use strict;
use warnings;

use JSON::MaybeXS;
use Data::Dumper;
use Solaris::kstat;
use Time::HiRes  qw( clock_nanosleep CLOCK_HIGHRES );
use IO::Async::Loop;
use Net::AMQP::RabbitMQ;

my $coder = JSON::MaybeXS->new->ascii;

my $hostname = qx{/bin/uname -n};
chomp($hostname);

my $loop = IO::Async::Loop->new;
my $mq    = Net::AMQP::RabbitMQ->new();
my $queue = "$hostname";

$mq->connect(
  # "nydevsol10.dev.bloomberg.com",
  "localhost",
  {
    user   => 'guest',
    pass   => 'guest',
  },
);

$mq->channel_open(1);

$mq->exchange_declare(1, "amq.direct",
  { exchange_type => 'direct',
    durable       => 1,
  }
);

$mq->queue_declare(1, $queue);

my $data_to_return =
[
  {
    'idl' => 100,
    'CPU' => 0
  },
  {
    'idl' => 99,
    'CPU' => 1
  },
  {
    'idl' => 98,
    'CPU' => 2
  },
  {
    'CPU' => 3,
    'idl' => 97
  },
  {
    'CPU' => 4,
    'idl' => 96
  },
  {
    'CPU' => 5,
    'idl' => 95
  },
  {
    'idl' => 94,
    'CPU' => 6
  },
  {
    'idl' => 93,
    'CPU' => 7
  },
  {
    'CPU' => 8,
    'idl' => 92
  },
  {
    'idl' => 91,
    'CPU' => 9
  },
  {
    'idl' => 90,
    'CPU' => 10
  },
  {
    'idl' => 89,
    'CPU' => 11
  },
  {
    'CPU' => 12,
    'idl' => 88
  },
  {
    'CPU' => 13,
    'idl' => 87
  },
  {
    'idl' => 86,
    'CPU' => 14
  },
  {
    'CPU' => 15,
    'idl' => 85
  },
  {
    'CPU' => 16,
    'idl' => 84
  },
  {
    'idl' => 83,
    'CPU' => 17
  },
  {
    'CPU' => 18,
    'idl' => 82
  },
  {
    'idl' => 81,
    'CPU' => 19
  },
  {
    'idl' => 80,
    'CPU' => 20
  },
  {
    'CPU' => 21,
    'idl' => 79
  },
  {
    'idl' => 78,
    'CPU' => 22
  },
  {
    'CPU' => 23,
    'idl' => 77
  },
  {
    'idl' => 76,
    'CPU' => 24
  },
  {
    'CPU' => 25,
    'idl' => 75
  },
  {
    'CPU' => 26,
    'idl' => 74
  },
  {
    'idl' => 73,
    'CPU' => 27
  },
  {
    'idl' => 72,
    'CPU' => 28
  },
  {
    'idl' => 71,
    'CPU' => 29
  },
  {
    'CPU' => 30,
    'idl' => 70
  },
  {
    'CPU' => 31,
    'idl' => 69
  },
  {
    'CPU' => 32,
    'idl' => 68
  },
  {
    'CPU' => 33,
    'idl' => 66
  },
  {
    'idl' => 65,
    'CPU' => 34
  },
  {
    'CPU' => 35,
    'idl' => 64
  },
  {
    'idl' => 63,
    'CPU' => 36
  },
  {
    'idl' => 62,
    'CPU' => 37
  },
  {
    'CPU' => 38,
    'idl' => 61
  },
  {
    'idl' => 60,
    'CPU' => 39
  },
  {
    'idl' => 59,
    'CPU' => 40
  },
  {
    'CPU' => 41,
    'idl' => 58
  },
  {
    'CPU' => 42,
    'idl' => 57
  },
  {
    'idl' => 56,
    'CPU' => 43
  },
  {
    'CPU' => 44,
    'idl' => 55
  },
  {
    'CPU' => 45,
    'idl' => 54
  },
  {
    'CPU' => 46,
    'idl' => 53
  },
  {
    'idl' => 52,
    'CPU' => 47
  },
  {
    'idl' => 51,
    'CPU' => 48
  },
  {
    'CPU' => 49,
    'idl' => 50
  },
  {
    'idl' => 49,
    'CPU' => 50
  },
  {
    'idl' => 48,
    'CPU' => 51
  },
  {
    'idl' => 47,
    'CPU' => 52
  },
  {
    'CPU' => 53,
    'idl' => 46
  },
  {
    'CPU' => 54,
    'idl' => 45
  },
  {
    'CPU' => 55,
    'idl' => 44
  },
  {
    'idl' => 43,
    'CPU' => 56
  },
  {
    'idl' => 42,
    'CPU' => 57
  },
  {
    'CPU' => 58,
    'idl' => 41
  },
  {
    'idl' => 40,
    'CPU' => 59
  },
  {
    'idl' => 39,
    'CPU' => 60
  },
  {
    'idl' => 38,
    'CPU' => 61
  },
  {
    'CPU' => 62,
    'idl' => 37
  },
  {
    'CPU' => 63,
    'idl' => 36
  },
  {
    'idl' => 35,
    'CPU' => 64
  },
  {
    'idl' => 34,
    'CPU' => 65
  },
  {
    'idl' => 33,
    'CPU' => 66
  },
  {
    'CPU' => 67,
    'idl' => 32
  },
  {
    'CPU' => 68,
    'idl' => 31
  },
  {
    'CPU' => 69,
    'idl' => 30
  },
  {
    'idl' => 29,
    'CPU' => 70
  },
  {
    'idl' => 28,
    'CPU' => 71
  },
  {
    'CPU' => 72,
    'idl' => 27
  },
  {
    'idl' => 26,
    'CPU' => 73
  },
  {
    'idl' => 25,
    'CPU' => 74
  },
  {
    'idl' => 24,
    'CPU' => 75
  },
  {
    'CPU' => 76,
    'idl' => 23
  },
  {
    'CPU' => 77,
    'idl' => 22
  },
  {
    'idl' => 21,
    'CPU' => 78
  },
  {
    'CPU' => 79,
    'idl' => 20
  },
  {
    'CPU' => 80,
    'idl' => 19
  },
  {
    'idl' => 18,
    'CPU' => 81
  },
  {
    'CPU' => 82,
    'idl' => 17
  },
  {
    'idl' => 16,
    'CPU' => 83
  },
  {
    'idl' => 15,
    'CPU' => 84
  },
  {
    'CPU' => 85,
    'idl' => 14
  },
  {
    'idl' => 13,
    'CPU' => 86
  },
  {
    'CPU' => 87,
    'idl' => 12
  },
  {
    'idl' => 11,
    'CPU' => 88
  },
  {
    'CPU' => 89,
    'idl' => 10
  },
  {
    'CPU' => 90,
    'idl' => 9
  },
  {
    'idl' => 8,
    'CPU' => 91
  },
  {
    'idl' => 7,
    'CPU' => 92
  },
  {
    'idl' => 6,
    'CPU' => 93
  },
  {
    'CPU' => 94,
    'idl' => 5
  },
  {
    'CPU' => 95,
    'idl' => 4
  },
  {
    'CPU' => 96,
    'idl' => 3
  },
  {
    'CPU' => 97,
    'idl' => 2
  },
  {
    'idl' => 1,
    'CPU' => 98
  },
  {
    'CPU' => 99,
    'idl' => 0
  },
  {
    'idl' => 100,
    'CPU' => 100
  },
  {
    'idl' => 93,
    'CPU' => 101
  },
  {
    'CPU' => 102,
    'idl' => 74
  },
  {
    'idl' => 100,
    'CPU' => 103
  },
  {
    'idl' => 100,
    'CPU' => 104
  },
  {
    'CPU' => 105,
    'idl' => 99
  },
  {
    'CPU' => 106,
    'idl' => 96
  },
  {
    'idl' => 100,
    'CPU' => 107
  },
  {
    'CPU' => 108,
    'idl' => 100
  },
  {
    'CPU' => 109,
    'idl' => 94
  },
  {
    'CPU' => 110,
    'idl' => 91
  },
  {
    'idl' => 100,
    'CPU' => 111
  },
  {
    'idl' => 98,
    'CPU' => 112
  },
  {
    'CPU' => 113,
    'idl' => 99
  },
  {
    'idl' => 99,
    'CPU' => 114
  },
  {
    'idl' => 99,
    'CPU' => 115
  },
  {
    'idl' => 100,
    'CPU' => 116
  },
  {
    'CPU' => 117,
    'idl' => 97
  },
  {
    'CPU' => 118,
    'idl' => 97
  },
  {
    'CPU' => 119,
    'idl' => 92
  },
  {
    'idl' => 92,
    'CPU' => 120
  },
  {
    'idl' => 96,
    'CPU' => 121
  },
  {
    'CPU' => 122,
    'idl' => 95
  },
  {
    'idl' => 98,
    'CPU' => 123
  },
  {
    'idl' => 100,
    'CPU' => 124
  },
  {
    'idl' => 97,
    'CPU' => 125
  },
  {
    'CPU' => 126,
    'idl' => 100
  },
  {
    'CPU' => 127,
    'idl' => 99
  },
  {
    'idl' => 100,
    'CPU' => 128
  },
  {
    'idl' => 95,
    'CPU' => 129
  },
  {
    'idl' => 99,
    'CPU' => 130
  },
  {
    'CPU' => 131,
    'idl' => 99
  },
  {
    'CPU' => 132,
    'idl' => 100
  },
  {
    'CPU' => 133,
    'idl' => 100
  },
  {
    'idl' => 97,
    'CPU' => 134
  },
  {
    'idl' => 99,
    'CPU' => 135
  },
  {
    'CPU' => 136,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 137
  },
  {
    'idl' => 91,
    'CPU' => 138
  },
  {
    'idl' => 99,
    'CPU' => 139
  },
  {
    'CPU' => 140,
    'idl' => 100
  },
  {
    'CPU' => 141,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 142
  },
  {
    'CPU' => 143,
    'idl' => 98
  },
  {
    'CPU' => 144,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 145
  },
  {
    'CPU' => 146,
    'idl' => 99
  },
  {
    'idl' => 94,
    'CPU' => 147
  },
  {
    'idl' => 99,
    'CPU' => 148
  },
  {
    'CPU' => 149,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 150
  },
  {
    'CPU' => 151,
    'idl' => 96
  },
  {
    'idl' => 100,
    'CPU' => 152
  },
  {
    'CPU' => 153,
    'idl' => 100
  },
  {
    'CPU' => 154,
    'idl' => 99
  },
  {
    'idl' => 98,
    'CPU' => 155
  },
  {
    'idl' => 96,
    'CPU' => 156
  },
  {
    'idl' => 98,
    'CPU' => 157
  },
  {
    'CPU' => 158,
    'idl' => 96
  },
  {
    'CPU' => 159,
    'idl' => 98
  },
  {
    'CPU' => 160,
    'idl' => 100
  },
  {
    'CPU' => 161,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 162
  },
  {
    'CPU' => 163,
    'idl' => 99
  },
  {
    'idl' => 96,
    'CPU' => 164
  },
  {
    'idl' => 93,
    'CPU' => 165
  },
  {
    'CPU' => 166,
    'idl' => 97
  },
  {
    'idl' => 100,
    'CPU' => 167
  },
  {
    'idl' => 100,
    'CPU' => 168
  },
  {
    'CPU' => 169,
    'idl' => 100
  },
  {
    'CPU' => 170,
    'idl' => 97
  },
  {
    'idl' => 95,
    'CPU' => 171
  },
  {
    'CPU' => 172,
    'idl' => 100
  },
  {
    'CPU' => 173,
    'idl' => 98
  },
  {
    'CPU' => 174,
    'idl' => 94
  },
  {
    'idl' => 97,
    'CPU' => 175
  },
  {
    'idl' => 99,
    'CPU' => 176
  },
  {
    'CPU' => 177,
    'idl' => 97
  },
  {
    'idl' => 97,
    'CPU' => 178
  },
  {
    'idl' => 94,
    'CPU' => 179
  },
  {
    'idl' => 100,
    'CPU' => 180
  },
  {
    'CPU' => 181,
    'idl' => 100
  },
  {
    'CPU' => 182,
    'idl' => 99
  },
  {
    'CPU' => 183,
    'idl' => 98
  },
  {
    'idl' => 96,
    'CPU' => 184
  },
  {
    'idl' => 100,
    'CPU' => 185
  },
  {
    'CPU' => 186,
    'idl' => 96
  },
  {
    'idl' => 97,
    'CPU' => 187
  },
  {
    'idl' => 100,
    'CPU' => 188
  },
  {
    'idl' => 100,
    'CPU' => 189
  },
  {
    'CPU' => 190,
    'idl' => 99
  },
  {
    'CPU' => 191,
    'idl' => 99
  },
  {
    'idl' => 97,
    'CPU' => 192
  },
  {
    'idl' => 0,
    'CPU' => 193
  },
  {
    'idl' => 100,
    'CPU' => 194
  },
  {
    'CPU' => 195,
    'idl' => 100
  },
  {
    'CPU' => 196,
    'idl' => 99
  },
  {
    'CPU' => 197,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 198
  },
  {
    'idl' => 99,
    'CPU' => 199
  },
  {
    'CPU' => 200,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 201
  },
  {
    'idl' => 92,
    'CPU' => 202
  },
  {
    'idl' => 99,
    'CPU' => 203
  },
  {
    'CPU' => 204,
    'idl' => 100
  },
  {
    'CPU' => 205,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 206
  },
  {
    'CPU' => 207,
    'idl' => 97
  },
  {
    'CPU' => 208,
    'idl' => 98
  },
  {
    'idl' => 100,
    'CPU' => 209
  },
  {
    'CPU' => 210,
    'idl' => 99
  },
  {
    'idl' => 92,
    'CPU' => 211
  },
  {
    'idl' => 99,
    'CPU' => 212
  },
  {
    'CPU' => 213,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 214
  },
  {
    'CPU' => 215,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 216
  },
  {
    'CPU' => 217,
    'idl' => 100
  },
  {
    'CPU' => 218,
    'idl' => 99
  },
  {
    'idl' => 97,
    'CPU' => 219
  },
  {
    'idl' => 95,
    'CPU' => 220
  },
  {
    'idl' => 99,
    'CPU' => 221
  },
  {
    'CPU' => 222,
    'idl' => 98
  },
  {
    'CPU' => 223,
    'idl' => 98
  },
  {
    'CPU' => 224,
    'idl' => 99
  },
  {
    'CPU' => 225,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 226
  },
  {
    'CPU' => 227,
    'idl' => 98
  },
  {
    'idl' => 99,
    'CPU' => 228
  },
  {
    'idl' => 94,
    'CPU' => 229
  },
  {
    'CPU' => 230,
    'idl' => 100
  },
  {
    'idl' => 98,
    'CPU' => 231
  },
  {
    'idl' => 99,
    'CPU' => 232
  },
  {
    'CPU' => 233,
    'idl' => 100
  },
  {
    'CPU' => 234,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 235
  },
  {
    'CPU' => 236,
    'idl' => 99
  },
  {
    'CPU' => 237,
    'idl' => 96
  },
  {
    'CPU' => 238,
    'idl' => 94
  },
  {
    'idl' => 97,
    'CPU' => 239
  },
  {
    'idl' => 98,
    'CPU' => 240
  },
  {
    'CPU' => 241,
    'idl' => 100
  },
  {
    'idl' => 100,
    'CPU' => 242
  },
  {
    'idl' => 99,
    'CPU' => 243
  },
  {
    'idl' => 97,
    'CPU' => 244
  },
  {
    'CPU' => 245,
    'idl' => 100
  },
  {
    'CPU' => 246,
    'idl' => 100
  },
  {
    'CPU' => 247,
    'idl' => 93
  },
  {
    'idl' => 88,
    'CPU' => 248
  },
  {
    'idl' => 100,
    'CPU' => 249
  },
  {
    'CPU' => 250,
    'idl' => 100
  },
  {
    'idl' => 99,
    'CPU' => 251
  },
  {
    'idl' => 99,
    'CPU' => 252
  },
  {
    'idl' => 100,
    'CPU' => 253
  },
  {
    'CPU' => 254,
    'idl' => 100
  },
  {
    'CPU' => 255,
    'idl' => 99
  }
];

while (1) {
  $mq->publish(1, $queue, $coder->encode( $data_to_return ));
  sleep(1);
}

